// IPMA weather-type code → Portuguese label.
// Lifted as-is from n8n/workflows/meteo-diario.json so values stay identical
// to whatever rows the n8n version was producing.
export const TIPOS_TEMPO: Record<number, string> = {
  1: "Céu limpo",
  2: "Pouco nublado",
  3: "Parcialmente nublado",
  4: "Muito nublado",
  5: "Chuva fraca",
  6: "Aguaceiros fracos",
  7: "Chuva",
  8: "Chuva forte",
  9: "Aguaceiros",
  10: "Trovoada com chuva",
  11: "Trovoada",
  12: "Neve",
  13: "Neve com chuva",
  14: "Granizo",
  15: "Nevoeiro",
  16: "Nublado com chuva fraca",
  17: "Aguaceiros",
  18: "Aguaceiros fortes",
  19: "Nevoeiro com chuva",
  20: "Granizo com chuva",
  21: "Aguaceiros com granizo",
  22: "Trovoada com chuva forte",
  23: "Trovoada com aguaceiros",
  24: "Neve e chuva",
  25: "Aguaceiros de neve",
  26: "Neve forte",
  27: "Céu limpo (noite)",
  28: "Pouco nublado (noite)",
  29: "Parcialmente nublado (noite)",
};
