-- Data-quality cleanup migration.
--
-- Three independent fixes bundled because they all touch praias/meteo_horaria
-- once and we want them applied atomically:
--   1. Null out bogus marine values for inland beaches (river/reservoir).
--      Open-Meteo's Marine API was returning sea data for some inland coords
--      because it snapped to the nearest sea cell — that data is meaningless.
--      The edge function now skips marine for non-coastal beaches; this migration
--      cleans up the historical writes.
--   2. Backfill praias.distrito from concelho. The initial APA import didn't
--      include this column. 154 of 155 concelhos map 1:1; "LAGOA" exists in
--      both Algarve and Açores and is disambiguated by longitude.
--   3. (No-op safeguard) skip writes to qualidade_agua are handled in the
--      edge function itself; nothing needed here.

-- 1. Null inland marine data
update meteo_horaria mh
set temp_agua = null,
    ondulacao_altura = null
from praias p
where mh.praia_id = p.id
  and p.tipo <> 'costeira'
  and (mh.temp_agua is not null or mh.ondulacao_altura is not null);

-- 2. Backfill distrito
update praias set distrito = case concelho
  when 'ABRANTES' then 'Santarém'
  when 'ALANDROAL' then 'Évora'
  when 'ALBUFEIRA' then 'Faro'
  when 'ALCANENA' then 'Santarém'
  when 'ALCOBAÇA' then 'Leiria'
  when 'ALCOUTIM' then 'Faro'
  when 'ALJEZUR' then 'Faro'
  when 'ALMADA' then 'Setúbal'
  when 'ANGRA DO HEROÍSMO' then 'Açores'
  when 'ARCOS DE VALDEVEZ' then 'Viana do Castelo'
  when 'ARGANIL' then 'Coimbra'
  when 'AVEIRO' then 'Aveiro'
  when 'AVIS' then 'Portalegre'
  when 'BEJA' then 'Beja'
  when 'BRAGA' then 'Braga'
  when 'CABECEIRAS DE BASTO' then 'Braga'
  when 'CALDAS DA RAINHA' then 'Leiria'
  when 'CALHETA' then 'Madeira'
  when 'CALHETA DE S. JORGE' then 'Açores'
  when 'CAMINHA' then 'Viana do Castelo'
  when 'CANTANHEDE' then 'Coimbra'
  when 'CASCAIS' then 'Lisboa'
  when 'CASTANHEIRA DE PÊRA' then 'Leiria'
  when 'CASTELO BRANCO' then 'Castelo Branco'
  when 'CASTRO DAIRE' then 'Viseu'
  when 'CASTRO MARIM' then 'Faro'
  when 'COIMBRA' then 'Coimbra'
  when 'CONSTÂNCIA' then 'Santarém'
  when 'CORUCHE' then 'Santarém'
  when 'CORVO' then 'Açores'
  when 'COVILHÃ' then 'Castelo Branco'
  when 'CUBA' then 'Beja'
  when 'CÂMARA DE LOBOS' then 'Madeira'
  when 'ESPINHO' then 'Aveiro'
  when 'ESPOSENDE' then 'Braga'
  when 'FAFE' then 'Braga'
  when 'FARO' then 'Faro'
  when 'FERREIRA DO ZÊZERE' then 'Santarém'
  when 'FIGUEIRA DA FOZ' then 'Coimbra'
  when 'FIGUEIRÓ DOS VINHOS' then 'Leiria'
  when 'FORNOS DE ALGODRES' then 'Guarda'
  when 'FREIXO DE ESPADA À CINTA' then 'Bragança'
  when 'FUNCHAL' then 'Madeira'
  when 'FUNDÃO' then 'Castelo Branco'
  when 'GONDOMAR' then 'Porto'
  when 'GOUVEIA' then 'Guarda'
  when 'GRÂNDOLA' then 'Setúbal'
  when 'GUARDA' then 'Guarda'
  when 'GÓIS' then 'Coimbra'
  when 'HORTA' then 'Açores'
  -- LAGOA handled below (longitude split)
  when 'LAGOS' then 'Faro'
  when 'LAJES DAS FLORES' then 'Açores'
  when 'LAJES DO PICO' then 'Açores'
  when 'LEIRIA' then 'Leiria'
  when 'LOULÉ' then 'Faro'
  when 'LOURINHÃ' then 'Lisboa'
  when 'LOUSÃ' then 'Coimbra'
  when 'MACEDO DE CAVALEIROS' then 'Bragança'
  when 'MACHICO' then 'Madeira'
  when 'MADALENA' then 'Açores'
  when 'MAFRA' then 'Lisboa'
  when 'MANTEIGAS' then 'Guarda'
  when 'MARCO DE CANAVESES' then 'Porto'
  when 'MARINHA GRANDE' then 'Leiria'
  when 'MATOSINHOS' then 'Porto'
  when 'MAÇÃO' then 'Santarém'
  when 'MIRA' then 'Coimbra'
  when 'MIRANDELA' then 'Bragança'
  when 'MOIMENTA DA BEIRA' then 'Viseu'
  when 'MONTEMOR-O-VELHO' then 'Coimbra'
  when 'MOURA' then 'Beja'
  when 'MOURÃO' then 'Évora'
  when 'MURTOSA' then 'Aveiro'
  when 'MÉRTOLA' then 'Beja'
  when 'NAZARÉ' then 'Leiria'
  when 'ODEMIRA' then 'Beja'
  when 'OEIRAS' then 'Lisboa'
  when 'OLEIROS' then 'Castelo Branco'
  when 'OLHÃO' then 'Faro'
  when 'OLIVEIRA DE FRADES' then 'Viseu'
  when 'OLIVEIRA DO HOSPITAL' then 'Coimbra'
  when 'OURÉM' then 'Santarém'
  when 'OVAR' then 'Aveiro'
  when 'PAMPILHOSA DA SERRA' then 'Coimbra'
  when 'PEDRÓGÃO GRANDE' then 'Leiria'
  when 'PENACOVA' then 'Coimbra'
  when 'PENALVA DO CASTELO' then 'Viseu'
  when 'PENAMACOR' then 'Castelo Branco'
  when 'PENELA' then 'Coimbra'
  when 'PENICHE' then 'Leiria'
  when 'POMBAL' then 'Leiria'
  when 'PONTA DELGADA' then 'Açores'
  when 'PONTA DO SOL' then 'Madeira'
  when 'PONTE DA BARCA' then 'Viana do Castelo'
  when 'PONTE DE SOR' then 'Portalegre'
  when 'PORTEL' then 'Évora'
  when 'PORTIMÃO' then 'Faro'
  when 'PORTO' then 'Porto'
  when 'PORTO MONIZ' then 'Madeira'
  when 'PORTO SANTO' then 'Madeira'
  when 'POVOAÇÃO' then 'Açores'
  when 'PRAIA DA VITÓRIA' then 'Açores'
  when 'PROENÇA-A-NOVA' then 'Castelo Branco'
  when 'PÓVOA DE LANHOSO' then 'Braga'
  when 'PÓVOA DE VARZIM' then 'Porto'
  when 'REGUENGOS DE MONSARAZ' then 'Évora'
  when 'RIBEIRA BRAVA' then 'Madeira'
  when 'RIBEIRA GRANDE' then 'Açores'
  when 'SABUGAL' then 'Guarda'
  when 'SANTA COMBA DÃO' then 'Viseu'
  when 'SANTA CRUZ' then 'Madeira'
  when 'SANTA CRUZ DA GRACIOSA' then 'Açores'
  when 'SANTA CRUZ DAS FLORES' then 'Açores'
  when 'SANTA MARIA DA FEIRA' then 'Aveiro'
  when 'SANTANA' then 'Madeira'
  when 'SANTIAGO DO CACÉM' then 'Setúbal'
  when 'SEIA' then 'Guarda'
  when 'SERNANCELHE' then 'Viseu'
  when 'SERTÃ' then 'Castelo Branco'
  when 'SESIMBRA' then 'Setúbal'
  when 'SETÚBAL' then 'Setúbal'
  when 'SEVER DO VOUGA' then 'Aveiro'
  when 'SILVES' then 'Faro'
  when 'SINES' then 'Setúbal'
  when 'SINTRA' then 'Lisboa'
  when 'SÁTÃO' then 'Viseu'
  when 'SÃO PEDRO DO SUL' then 'Viseu'
  when 'SÃO ROQUE DO PICO' then 'Açores'
  when 'SÃO VICENTE' then 'Madeira'
  when 'TAVIRA' then 'Faro'
  when 'TERRAS DE BOURO' then 'Braga'
  when 'TOMAR' then 'Santarém'
  when 'TONDELA' then 'Viseu'
  when 'TORRES VEDRAS' then 'Lisboa'
  when 'TÁBUA' then 'Coimbra'
  when 'VAGOS' then 'Aveiro'
  when 'VALE DE CAMBRA' then 'Aveiro'
  when 'VALPAÇOS' then 'Vila Real'
  when 'VELAS' then 'Açores'
  when 'VIANA DO CASTELO' then 'Viana do Castelo'
  when 'VIEIRA DO MINHO' then 'Braga'
  when 'VILA DE REI' then 'Castelo Branco'
  when 'VILA DO BISPO' then 'Faro'
  when 'VILA DO CONDE' then 'Porto'
  when 'VILA DO PORTO' then 'Açores'
  when 'VILA FRANCA DO CAMPO' then 'Açores'
  when 'VILA NOVA DE CERVEIRA' then 'Viana do Castelo'
  when 'VILA NOVA DE GAIA' then 'Porto'
  when 'VILA REAL DE SANTO ANTÓNIO' then 'Faro'
  when 'VILA VELHA DE RÓDÃO' then 'Castelo Branco'
  when 'VILA VERDE' then 'Braga'
  when 'VINHAIS' then 'Bragança'
  when 'ÍLHAVO' then 'Aveiro'
  when 'ÓBIDOS' then 'Leiria'
end
where concelho <> 'LAGOA';

-- LAGOA: longitude < -20 → Açores (São Miguel), else Algarve.
update praias set distrito = case
  when longitude < -20 then 'Açores'
  else 'Faro'
end
where concelho = 'LAGOA';
